### ISSUE TITLE
If there are no imports in a file, the oranizeImports adds unnessecary whitespace on top

### ISSUE THREAD

**Issue by nuIIpointerexception** [llogick/zigscient#13]
### Zig Version

master

### This Project's Version

master

### Client / Code Editor / Extensions

Zed, usage like in zls instructions.

### Steps to Reproduce and Observed Behavior

 1. zed config (im sure its not really necessary though?):
```zig
{
  "languages": {
    "Zig": {
      "format_on_save": "language_server",
      "code_actions_on_format": {
        "source.fixAll": true,
        "source.organizeImports": true
      }
    }
  },
  "lsp": {
    "zigscient": {
      "initialization_options": {
        "warn_style": true,
        "semantic_tokens": "full",
        "enable_build_on_save": true,
        "build_on_save_args": ["check", "-Dtarget=x86_64-linux-gnu"]
      }
    }
  }
}
```

2. create a file without any imports.
3. add a space anywhere so we can let it auto format
4. save the file
5. repeat this and see how we can move our code down, spooky!

### Expected Behavior

It shouldnt add a whitespace. let alone keep adding more and more on each save.

**Comment by llogick** [comment]
Obligatory https://xkcd.com/1172/

Fix in 11447327924ae57a98d3666c6aa08e4df56a6135

Thank You !
