### ISSUE TITLE
Put members first in "files as structs" when organizing imports

### ISSUE THREAD

**Issue by mattnite** [llogick/zigscient#9]
When I organize the following contents:

```zig
gpa: std.mem.Allocator,
connections: std.DoublyLinkedList(Node) = .{},

const std = @import("std");

const xev = @import("xev");
const HTTP_Server = @This();
const Node = struct {
    read_comp: xev.Completion,
};
```

I get the result:

```zig
const std = @import("std");

const xev = @import("xev");

gpa: std.mem.Allocator,
connections: std.DoublyLinkedList(Node) = .{},

const HTTP_Server = @This();
const Node = struct {
    read_comp: xev.Completion,
};
```

I think it's best to put members at the top of the file so it's easy to understand what makes up the struct. I would love to see this as the default and/or a config!

**Comment by llogick** [comment]
I agree, as for other options -- we can simply have separate code actions, eg

"Organize Imports (Imports First)"
"Organize Imports (Imports Last)"
"Organize Imports (Fields Last)"
